{
    "name": "pablings/barbershop",
    "description": "Pabling's Barbershop Management System",
    "type": "project",
    "version": "1.0.0",
    "keywords": ["barbershop", "booking", "management"],
    "license": "MIT",
    "require": {
        "php": ">=7.4",
        "ext-pdo": "*",
        "ext-pdo_pgsql": "*",
        "ext-mbstring": "*",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-session": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        },
        "files": [
            "connection.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "scripts": {
        "test": "phpunit",
        "check-extensions": "php -m | grep -E '(pdo|pgsql|mbstring|curl|json)'",
        "serve": "php -S localhost:8000"
    },
    "config": {
        "platform": {
            "php": "7.4"
        },
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "extra": {
        "branch-alias": {
            "dev-main": "1.0.x-dev"
        }
    }
}
