services:
  - type: web
    name: pablings-barbershop
    env: php
    plan: free
    buildCommand: |
      # Install PostgreSQL extension
      apt-get update
      apt-get install -y php-pgsql
      # or if using different package manager
      # apk add --no-cache php81-pdo_pgsql php81-pgsql
    startCommand: |
      # Start PHP built-in server
      php -S 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pablings-database
          property: connectionString
