services:
  - type: web
    name: pablings-barbershop
    env: php
    plan: free
    region: singapore
    buildCommand: |
      # Update package list
      apt-get update
      
      # Install required PHP extensions
      apt-get install -y \
        php-pgsql \
        php-pdo \
        php-mbstring \
        php-curl \
        php-xml \
        php-zip \
        php-gd \
        php-intl
      
      # Install Composer if not present
      if ! command -v composer &> /dev/null; then
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
      fi
      
      # Install dependencies
      composer install --no-dev --optimize-autoloader
      
      # Set proper permissions
      chmod -R 755 .
      
    startCommand: |
      # Start PHP built-in server on the port provided by Render
      php -S 0.0.0.0:$PORT -t .
      
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pablings-database
          property: connectionString
      - key: PHP_MEMORY_LIMIT
        value: 256M
      - key: PHP_MAX_EXECUTION_TIME
        value: 300
      - key: TZ
        value: Asia/Manila
      - key: DEBUG
        value: false

databases:
  - name: pablings-database
    databaseName: pablings_barbershop
    user: pablings_user
    region: singapore
    plan: free
